language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      node_js: "4"
    - os: linux
      dist: trusty
      sudo: false
      node_js: "6"
    - os: linux
      dist: trusty
      sudo: false
      node_js: "7"
    - os: osx
      osx_image: xcode8.3
      node_js: "6"
    - os: osx
      osx_image: xcode8.3
      node_js: "7"
