language: node_js
node_js:
  - "4"
  - "6"
  - "7"
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode8.3
  allow_failures:
    - os: osx
      node_js: "4"
